- type: antag
  id: MothershipCore
  name: roles-antag-mothership-core-name
  antagonist: true
  setPreference: true
  objective: roles-antag-mothership-core-objective
  guides: [ Xenoborgs ]
  tags:
  - OffStation
  - Roundstart
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs

- type: antagSpecifier
  parent: RestrictedAntag
  id: MothershipCore
  prefRoles: [ MothershipCore ]
  spawnerPrototype: SpawnPointGhostRoleMothershipCore
  briefing:
    text: mothership-welcome
    color: BlueViolet
    sound: /Audio/Ambience/Antag/xenoborg_start.ogg
  mindRoles:
  - MindRoleMothershipCore

- type: antag
  id: Xenoborg
  name: roles-antag-xenoborg-name
  antagonist: true
  setPreference: true
  objective: roles-antag-xenoborg-objective
  guides: [ Xenoborgs ]
  tags:
  - OffStation
  - Roundstart
  - Converted
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BaseXenoborg
  prefRoles: [ Xenoborg ]
  spawnerPrototype: SpawnPointGhostRoleXenoborg

- type: antagSpecifier
  parent: BaseXenoborg
  id: Xenoborg
  briefing:
    text: xenoborgs-welcome
    color: BlueViolet
    sound: /Audio/Ambience/Antag/xenoborg_start.ogg
  mindRoles:
  - MindRoleXenoborg